### ISSUE TITLE
Module on CPAN does not have version number

### ISSUE THREAD

**Issue by szabgab** [srchulo/Short--URL#2]
I think Dist::Zilla can be told to embed one in the module.

**Comment by srchulo** [comment]
Hi @szabgab ,

On MetaCPAN I am seeing a version number:

https://metacpan.org/pod/Short::URL

Do you mean on actual cpan.org? I tried to check there, but the search form actually submits to metacpan.org. Or do you mean in the repo there is no version number?

**Comment by srchulo** [comment]
Actually, on cpan.org I'm also seeing a version in the download and in the documentation:

http://search.cpan.org/dist/Short-Url/lib/Short/Url.pm

**Comment by szabgab** [comment]
Those are version numbers on the distribution not in the source code of the module.

```perl -MShort::URL -E'say $Short::URL::VERSION'```

is empty.

**Comment by srchulo** [comment]
Sorry this took me so long to fix. I just updated it and version .012 Should be uploaded soon with the version number in the file.

**Comment by szabgab** [comment]
:+1:
